### ISSUE TITLE
Crashing after selecting save file to play on

### ISSUE THREAD

**Issue by Veitaserum4** [kellsnc/sadx-multiplayer#2]
I have tried absolutely everything to get this to work- I was first trying this on linux through proton, but that doesn't work well with the input mod, so now on windows it crashes right after selecting a save file that I have only beaten up to Emerald Coast in
Mods I have installed:
![image](https://github.com/kellsnc/sadx-multiplayer/assets/63559389/2617e5d1-1b2d-4b2d-ae47-0dff8446a07e)
Codes:
![image](https://github.com/kellsnc/sadx-multiplayer/assets/63559389/f7c3a865-c102-4863-9a24-01121f67068b)
![image](https://github.com/kellsnc/sadx-multiplayer/assets/63559389/cc4ed2cd-a237-4930-afea-ff6f0b1cefc1)
Graphics:
![image](https://github.com/kellsnc/sadx-multiplayer/assets/63559389/5a92b01d-4560-4976-8ee2-a3bd356a12e1)
Error I get:
![image](https://github.com/kellsnc/sadx-multiplayer/assets/63559389/17c086eb-99bb-4a37-b832-f39c669e5049)

**Comment by Veitaserum4** [comment]
I completely reinstalled the SADX mod loader using this: https://sadxmodinstaller.unreliable.network 
now I'm able to select my save file, but multiplayer is greyed out, I only have Multiplayer and Input Mod enabled
![image](https://github.com/kellsnc/sadx-multiplayer/assets/63559389/a9695fdf-3fef-490a-9d54-80cb1db38711)

**Comment by kellsnc** [comment]
Hello, it's greyed out because you need to complete levels ^^

**Comment by Veitaserum4** [comment]
> Hello, it's greyed out because you need to complete levels ^^

I completed emerald coast

**Comment by Veitaserum4** [comment]
> Hello, it's greyed out because you need to complete levels ^^

I just downloaded a 100% save file and now it works, so how far along in the game do I have to play for it to work? I would like to play all, if not most of the beginning with someone

**Comment by kellsnc** [comment]
You cannot play multiplayer in adventure mode yet, only individual levels for now. And uhm completing EC should've been enough?

**Comment by Veitaserum4** [comment]
> You cannot play multiplayer in adventure mode yet, only individual levels for now. And uhm completing EC should've been enough?

Oh, I see. Well, now when I enable the Dreamcast Conversion Mod and the Lantern Engine mod with the Multiplayer, I get the same error as in my first post. I can play without it but I have searched all over the internet for an answer and can't find anything

**Comment by kellsnc** [comment]
The multiplayer mod needs to be below these two mods, you might need to reorder your mods?

**Comment by Veitaserum4** [comment]
> The multiplayer mod needs to be below these two mods, you might need to reorder your mods?
I reordered them like this and I still get that same crash
![image](https://github.com/kellsnc/sadx-multiplayer/assets/63559389/8c0afb39-8990-41a3-9f5e-6ac37f9a1bcf)

**Comment by kellsnc** [comment]
Sorry, I missed your comment

I said you should put the multiplayer mod below the others, in your screenshot it is above ^^
