### ISSUE TITLE
Soft-lock in Tails' story after saving in the Mystic Ruins flashback sequence

### ISSUE THREAD

**Issue by jroyvde** [kellsnc/sadx-multiplayer#3]
With the multiplayer mod enabled, loading into Tails' story after having saved during the flashback sequence results in the following soft-lock, with the player being moved back and forth endlessly between the city area and the altar area. No player input is possible, not even pausing the game.

https://github.com/kellsnc/sadx-multiplayer/assets/54386705/337ee3ef-f63a-42b9-8757-b2535766a9ad

I had the Dreamcast Conversion mod enabled in this recording, but I've also tested with it disabled and the issue still occurs.

**Comment by kellsnc** [comment]
Thanks for the report and sorry for the inconvenience.

Two things:
- Does it fix itself if you disable the mod? If not I can fix the save file if needed.
- Can you send the save file so I can test faster? Lacking time recently...

**Comment by jroyvde** [comment]
Sure, have attached the save file here :)

[SonicDX01.snc.zip](https://github.com/user-attachments/files/16175756/SonicDX01.snc.zip)

No need to fix it - disabling the mod does make the issue go away.

**Comment by kellsnc** [comment]
Thank you! The fix will be in the next release, in the meantime you can disable the mod when playing through a story :)
